## Chapter 5 : Basic Numpy Arrays

---
* Author:  [Yuttapong Mahasittiwat](mailto:khala1391@gmail.com)
* Technologist | Data Modeler | Data Analyst
* [YouTube](https://www.youtube.com/khala1391)
* [LinkedIn](https://www.linkedin.com/in/yuttapong-m/)
---

### Array Attributes

In [123]:
import numpy as np

In [145]:
np.random.seed(20)  # reset after use
s1 = np.random.randint(10,size =6)
print(s1)
print("reset after use")
s2 = np.random.randint(10,size =6)
print(s2)

[3 9 4 6 7 2]
reset after use
[0 6 8 5 3 0]


In [159]:
rng = np.random.default_rng(seed=1701)  # always reproduce
x1 = rng.integers(10,size =6)
x2 = rng.integers(10,size =(3,4))
x3 = rng.integers(10,size =(3,4,5))

In [161]:
print("x3 ndim:", x3.ndim)
print("x3 ndim:", x3.shape)
print("x3 ndim:", x3.size)
print("x3 ndim:", x3.dtype)

x3 ndim: 3
x3 ndim: (3, 4, 5)
x3 ndim: 60
x3 ndim: int64


In [163]:
x3

array([[[4, 3, 5, 5, 0],
        [8, 3, 5, 2, 2],
        [1, 8, 8, 5, 3],
        [0, 0, 8, 5, 8]],

       [[5, 1, 6, 2, 3],
        [1, 2, 5, 6, 2],
        [5, 2, 7, 9, 3],
        [5, 6, 0, 2, 0]],

       [[2, 9, 4, 3, 9],
        [9, 2, 2, 4, 0],
        [0, 3, 0, 0, 2],
        [3, 2, 7, 4, 7]]], dtype=int64)

### Array Indexing

In [166]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [168]:
x1[0]

9

In [170]:
x1[4]

8

In [172]:
x1[-1]

6

In [174]:
x1[-2]

8

In [176]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [178]:
x2[0]

array([3, 1, 3, 7], dtype=int64)

In [180]:
x2[0,0]

3

In [182]:
x2[2,0]

0

In [184]:
x2[2,-1]

9

In [186]:
x2[0,0]=12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [188]:
# fix datatype ( data will be truncated)
x1[0]= 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

### Array Slicing

In [249]:
# x[start:stop(excluded):step]

x1[:3]

array([3, 4, 0], dtype=int64)

In [193]:
x1[3:]

array([3, 8, 6], dtype=int64)

In [195]:
x1[1:4]

array([4, 0, 3], dtype=int64)

In [197]:
x1[::2]

array([3, 0, 8], dtype=int64)

In [199]:
x1[1::2]

array([4, 3, 6], dtype=int64)

In [205]:
# all element, reversed
x1[::-1]

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [203]:
x1[4::-2]

array([8, 0, 3], dtype=int64)

In [209]:
x1[:1]  # index for stop is excluding

array([3], dtype=int64)

In [211]:
x1[:2]

array([3, 4], dtype=int64)

In [207]:
# multidimensional subarrays
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [213]:
x2[:2,:3]    # index for stop is excluding

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [215]:
x2[:3,::2]    # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [217]:
x2[::-1,::-1] # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

In [219]:
x2[:,0] # first column of x2

array([12,  4,  0], dtype=int64)

In [223]:
x2[0,:]    # first row of x2

array([12,  1,  3,  7], dtype=int64)

In [225]:
x2[0]    # first row of x2

array([12,  1,  3,  7], dtype=int64)

In [227]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [235]:
x2_sub = x2[:2,:2]    # JUST COPYING VIEW
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [231]:
x2_sub[0,0] = 99
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [239]:
x2   # also changed at original ones

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [241]:
# creating copy by using copy()
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [243]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  1],
       [ 4,  0]], dtype=int64)

In [245]:
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [247]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

### Reshaping arrays

In [251]:
grid = np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [253]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [265]:
# no-copy view
grid2 = np.arange(1,10)
grid2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [267]:
grid2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [269]:
x =np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [273]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [275]:
x

array([1, 2, 3])

In [277]:
# newaxis
x[np.newaxis,:]  # row vector via newaxis

array([[1, 2, 3]])

In [283]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

In [293]:
x

array([1, 2, 3])

In [291]:
x.reshape((1,-1))   # row vector

array([[1, 2, 3]])

In [289]:
x.reshape((-1,1)) # column vector

array([[1],
       [2],
       [3]])

In [299]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [301]:
z = np.array([99,99,99])
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [303]:
# 2D
grid = np.array([[1,2,3],
                [4,5,6]])

In [307]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [309]:
np.concatenate([grid,grid], axis=1)  # stack by column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [313]:
# vstack
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [317]:
newy = np.array([[99],
                [99]])
np.hstack([grid,newy])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [321]:
# np.hstack([grid,y])  # stack cannot broadcast

In [ ]:
# np.dstack used for 3rd axis

### Array concatenate and splitting 

In [341]:
x =[1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])    #split at index 3,5   # N+1 arrays
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [343]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [347]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [351]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
