## Chapter6 : computation on numpy arrays: Universal functions

---
* Author:  [Yuttapong Mahasittiwat](mailto:khala1391@gmail.com)
* Technologist | Data Modeler | Data Analyst
* [YouTube](https://www.youtube.com/khala1391)
* [LinkedIn](https://www.linkedin.com/in/yuttapong-m/)
---

---
* Author:  [Yuttapong Mahasittiwat](mailto:khala1391@gmail.com)
* Technologist | Data Modeler | Data Analyst
* [YouTube](https://www.youtube.com/khala1391)
* [LinkedIn](https://www.linkedin.com/in/yuttapong-m/)
---

In [1]:
import numpy as np

In [20]:
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
    
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [26]:
big_array = rng.integers(1, 100, size=1000000)
# %timeit compute_reciprocals(big_array)   # very SLOW due to LOOP

4.44 s ± 456 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
big_array.size

1000000

In [41]:
print(compute_reciprocals(values))   # loop
print(1/values)  # not loop

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [43]:
# %timeit (1.0/big_array)   # much FASTER

9.33 ms ± 442 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
np.arange(5), np.arange(1,6)

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

In [47]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [53]:
x = np.arange(9).reshape(3,3)
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

### explore numpy's ufuncs

**Array Arithmetic**

In [3]:
x = np.arange(4)
print("x   =",x)
print("x+5 =",x+5)
print("x-5 =",x-5)
print("x*2 =",x*2)
print("x/2 =",x/2)
print("x//2 =",x//2)

x   = [0 1 2 3]
x+5 = [5 6 7 8]
x-5 = [-5 -4 -3 -2]
x*2 = [0 2 4 6]
x/2 = [0.  0.5 1.  1.5]
x//2 = [0 0 1 1]


In [9]:
print("-x  =",-x)
print("x **2 =", x **2)
print("x% 2 = ", x % 2)

-x  = [ 0 -1 -2 -3]
x **2 = [0 1 4 9]
x% 2 =  [0 1 0 1]


In [11]:
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [13]:
np.add(x,2)

array([2, 3, 4, 5])

**Absolute Value**

In [19]:
x = np.array([-2,-1,0,1,2])

In [21]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
np.abs(x)

array([2, 1, 0, 1, 2])

**Trigometric**

In [25]:
theta = np.linspace(0,np.pi,3)

In [29]:
print("theta   =", theta)
print("sin(theta)   =", np.sin(theta))
print("cos(theta)   =", np.cos(theta))
print("tan(theta)   =", np.tan(theta))

theta   = [0.         1.57079633 3.14159265]
sin(theta)   = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)   = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)   = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1,0,1]
print()

**Exponents and logarithms**

In [5]:
x = [1,2,3]
print("x =", x)
print("e^x=", np.exp(x))
print("2^x=", np.exp2(x))
print("3^x=", np.power(3.,x))

x = [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3.  9. 27.]


In [7]:
x =[1,2,4,10]
print("x   =", x)
print("ln(x)  =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x)  =", np.log10(x))

x   = [1, 2, 4, 10]
ln(x)  = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [17]:
x=[0,.001,.01,.1]
print("exp((x) - 1 = ", np.expm1(x))
print("log(1+x)    = ",  np.log1p(x))

exp((x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1+x)    =  [0.         0.0009995  0.00995033 0.09531018]


**Specialized Ufunc**

In [19]:
from scipy import special

### Advance Ufunc

**specfiying Output**

In [21]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y

array([ 0., 10., 20., 30., 40.])

In [23]:
y = np.zeros(10)
np.power(2,x, out=y[::2])
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

**Aggregation**

more information: [ufunc](https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs)

highlight ufunc.* function:
-  reduce
-  accumulate
-  outer
-  at
-  reduceat

In [25]:
x = np.arange(1,6)
np.add.reduce(x)

15

In [27]:
np.multiply.reduce(x)

120

In [29]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [33]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [41]:
# dedicated np function
print("np.sum :", np.sum(x))
print("np.product :", np.product(x))
print("np.cumsum :", np.cumsum(x))
print("np.cumproduct :", np.cumproduct(x))

np.sum : 15
np.product : 120
np.cumsum : [ 1  3  6 10 15]
np.cumproduct : [  1   2   6  24 120]


**Outer Product**

In [43]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])